baseURL = "https://example.com"
title = "Fuji Demo"
theme = "fuji"
hasCJKLanguage = true
enableEmoji = true
enableRobotsTXT = true
disableKinds = ["taxonomyTerm"]

## Change this two to switch between different language
languageCode = "en"  # For RSS, view https://www.rssboard.org/rss-language-codes
defaultContentLanguage = "en"  # For HTML page, now support: en, zh-hans, zh-hant, ja, nl

summaryLength = 100 # Custom cummary length, add <!--more--> in post file to custom split point
paginate = 10

# googleAnalytics = "UA-000000000-0" # Set your Google Analytics UA here, or comment out to disable

[permalinks]
  post = "/:filename/" # Custom post links, e.g. "/:year/:month/:title/"

[params]
  author = "DSRKafuU" # You can also set author in post front matter individually
  subTitle = "This is a Sub Title"

  # Word counter and read time indicator in post metadata
  showWordCounter = true
  # showReadTime = true

  # Open Graph & Twitter Card variables
  # You can also set description and images in post front matter individually
  description = "A minimal hugo theme powered by Primer CSS."
  images = ["img/og.png"] # This will use the image called og.png in static/img folder

  # Posts shown in homepage
  mainSections = ["post"]

  # Bangumi image chart id
  # bgmImageChart = "000000"

  # Show scroll to top button
  scrollTop = true

  # License
  license = "Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License (CC BY-NC-SA 4.0)"
  licenseLink = "http://creativecommons.org/licenses/by-nc-sa/4.0/"

  # Comments
  # utterances, see: https://utteranc.es/
  # utterancesRepo = "[ENTER REPO HERE]"
  # utterancesIssueTerm = "pathname"
  # utterancesTheme = "github-light"

  # Disqus, see: https://disqus.com/admin/install/platforms/universalcode/
  # disqusComment = false
  # disqusShortname = "[ENTER YOUR DISQUS SHORTNAME HERE]"

  # custom lazyload placeholder
  # 16:9
  lazyPlaceholder = "/lazyload/dsrca_loading_480x270.svg"
  # 32:9
  lazyPlaceholderRow = "/lazyload/dsrca_loading_960x270.svg"
  # 8:9
  lazyPlaceholderCol = "/lazyload/dsrca_loading_480x540.svg"

  # enable this to fetch css & js from jsDelivr CDN
  useCDN = true

  # site global fixed mode aplayer 
  # playerName = "..." # Audio title or name
  # playerArtist = "..." # Audio artist
  # playerURL = "..." # Audio URL, support aac, mp3, wav and ogg
  # playerCover = "..." # Audio cover

[markup]
  [markup.highlight]
    style = "monokailight"

  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3

[taxonomies]
  tag = "tags"

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Archives"
    url = "/archives/"
    weight = 2
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 3

  [[menu.link]]
    name = "GitHub"
    url = "https://github.com/amzrk2"
    weight = 1
  [[menu.link]]
    name = "Twitter"
    url = "https://twitter.com/amzrk2"
    weight = 2
  [[menu.link]]
    name = "bilibili"
    url = "https://space.bilibili.com/19767474"
    weight = 3
